[mypy]
python_version = 3.11
mypy_path = src
incremental = False
follow_imports_for_stubs = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-nio.*]
ignore_missing_imports = True

[mypy-meshtastic.*]
ignore_missing_imports = True

[mypy-serial.*]
ignore_missing_imports = True

[mypy-pubsub.*]
ignore_missing_imports = True

[mypy-haversine.*]
ignore_missing_imports = True

[mypy-s2sphere.*]
ignore_missing_imports = True

[mypy-staticmaps.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-markdown.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
follow_imports = skip

[mypy-numpy.*]
follow_imports = skip
