target-version = "py311"

# Generic, formatter-friendly config.
select = ["B", "D3", "E", "F"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
ignore = ["E501"]

[per-file-ignores]
"src/mmrelay/meshtastic_utils.py" = ["E402", "I001"]
"src/mmrelay/matrix_utils.py" = ["E402", "I001"]
